version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: zstore
      POSTGRES_USER: kyte
      POSTGRES_PASSWORD: utjhubq12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    environment:
      PG_USER: kyte
      PG_PASSWORD: utjhubq12345
      PG_DB: zstore
      PG_HOST: db
      PG_PORT: 5432
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./client/public/assets:/app/client/public/assets
      - ./server:/app  # маппинг сервера из локальной папки в контейнер (укажите свой путь!)
      - /app/node_modules # чтобы зависимости оставались внутри контейнера
    command: npm start  # запуск nodemon

volumes:
  pgdata: